# Generated by Django 5.2.6 on 2025-10-12 22:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StitchType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Full name of the stitch (e.g., Single Crochet)', max_length=100, unique=True)),
                ('abbreviation', models.CharField(help_text='Common abbreviation (e.g., SC)', max_length=10, unique=True)),
            ],
            options={
                'verbose_name': 'Stitch Type',
                'verbose_name_plural': 'Stitch Types',
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Descriptive name (e.g., Worsted Weight Yarn, 4.0mm Hook)', max_length=100)),
                ('type', models.CharField(choices=[('YARN', 'Yarn'), ('HOOK', 'Hook'), ('NOTION', 'Notion'), ('OTHER', 'Other')], default='YARN', max_length=50)),
                ('gauge_info', models.CharField(blank=True, help_text='Optional: Tension or gauge specifications for this material.', max_length=255, null=True)),
            ],
            options={
                'verbose_name_plural': 'Materials',
                'unique_together': {('name', 'type')},
            },
        ),
        migrations.CreateModel(
            name='Pattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, help_text='Detailed summary of the pattern.')),
                ('instructions', models.TextField(help_text='Step-by-step crochet instructions.')),
                ('difficulty_level', models.CharField(choices=[('EASY', 'Easy'), ('MEDIUM', 'Medium'), ('HARD', 'Hard'), ('EXPERT', 'Expert')], default='EASY', max_length=50)),
                ('is_public', models.BooleanField(default=True, help_text='If checked, the pattern is visible to all users.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patterns', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PatternMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.CharField(help_text="Specific amount needed (e.g., '3 skeins', '1 hook')", max_length=100)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crochet.material')),
                ('pattern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='required_materials', to='crochet.pattern')),
            ],
            options={
                'verbose_name': 'Required Material',
                'verbose_name_plural': 'Required Materials',
                'unique_together': {('pattern', 'material')},
            },
        ),
        migrations.CreateModel(
            name='PatternStitch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pattern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='used_stitches', to='crochet.pattern')),
                ('stitch_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crochet.stitchtype')),
            ],
            options={
                'verbose_name': 'Pattern Stitch',
                'verbose_name_plural': 'Pattern Stitches',
                'unique_together': {('pattern', 'stitch_type')},
            },
        ),
    ]
